### ISSUE TITLE
a question about designing my own board for a gbazero

### ISSUE THREAD

**Issue by steventylerseanherr** [AEFeinstein/gbaZero#3]
hi
i plan to follow in your footsteps and build a pi zero powered gba myself just with support for aftermarket gba mods
and i was wondering if you thought it might be possible to make a new board that supports all / most of the after market gba parts
mostly things like the funnyplaying usb-c power pak and the funnyplaying ita screen and shells

just wondering before i go digging into learning hardware design and stuff lol

**Comment by AEFeinstein** [comment]
If you're asking if it's possible for me to do it, nah, I don't have the time. If you're asking if it's possible in general, probably?

You could take the basic board shape here and modify it to be more electrically like a GBA. You'd have to more closely mimic things like the screen connector and driver, battery connectors, and anything else you'd want to be compatible with mods.
